src/BnBTree.jl, src/model.jl, src/solver.jl, test/basic.jl, test/runtests.jl
=> Don't copy the whole model for every node

src/BnBTree.jl, src/MINLPBnB.jl, src/model.jl, src/solver.jl, test/basic.jl, test/power_models_acp.jl, test/power_models_socwr.jl, test/runtests.jl
Add option: `strong_restart::Bool`
If set to `true` strong branching will be restarted if child is infeasible.
* bound of that variable is updated for all possible branches
=> Option for restarting strong branching if child is infeasible

src/BnBTree.jl, test/basic.jl
Return infeasible if no branch possible or return relaxation status if not `:Optimal` or `:LocalOptimal`
=> Handle infeasible

src/model.jl
set lower and upper bounds (JuMP doesn't do that automatically)
=> Bugfix setcategory bin

src/BnBTree.jl, src/bb_strategies.jl, src/table_log.jl, test/pod.jl
If it's not the first step then Infeasible is strong branching is only local and not global. Therefore don't break
=> Bugfix: Infeasible in strong branching is only local

src/BnBTree.jl, src/bb_gains.jl, src/bb_inits_and_defaults.jl, src/bb_strategies.jl, src/bb_user_limits.jl
Add relaxation_state for better :Error handeling in relaxation
=> Bugfix empty node branch list

README.md, readme/user_limits.md, src/BnBTree.jl, src/MINLPBnB.jl, src/bb_user_limits.jl, src/model.jl, src/solver.jl, test/basic.jl, test/power_models_socwr.jl, test/runtests.jl
Options for traverse strategy 
Also:
- mip_gap default to 0.01% 
- branching strategy is now `StrongPseudoCost`
=> traverse strategy 

docs/src/options.md, src/BnBTree.jl, src/MINLPBnB.jl, src/bb_strategies.jl, src/solver.jl, test/parallel.jl, test/pod.jl, test/power_models_socwr.jl, test/runtests.jl, test/user_limits.jl
Percentage value for strong branching instead of number of variables.
=> Feature strong perc

src/solver.jl, test/power_models_socwr.jl
If option was set to false it didn't pass the combine options function :/
=> Bugfix bool options

src/solver.jl, test/functions.jl
=> Feature warning option

docs/src/options.md, src/bb_user_limits.jl, src/solver.jl, test/parallel.jl, test/user_limits.jl
=> Default 0.0001
@ccoffrin I don't know whether that's of interest for the experiments but probably not.
=> Change mip_gap from percentage to what everyone else is doing :D

.travis.yml, README.md, docs/make.jl, docs/src/index.md, docs/src/options.md, src/BnBTree.jl, src/Juniper.jl, src/bb_integral_or_branch.jl, src/model.jl, src/solver.jl, test/basic.jl, test/functions.jl, test/parallel.jl, test/pod.jl, test/power_models_acp.jl, test/power_models_socwr.jl, test/runtests.jl, test/user_limits.jl
=> Feature juniper

docs/src/options.md, src/BnBTree.jl, src/Juniper.jl, src/bb_integral_or_branch.jl, src/bb_strategies.jl, src/bb_type_correct.jl, src/fpump.jl, src/solver.jl
Added two options for tolerance
=> atol + feasibility_pump_tolerance_counter

src/BnBTree.jl, src/Juniper.jl, src/model.jl, src/solver.jl, test/parallel.jl, test/user_limits.jl
=> more resoanble processor counter in parallel

.gitlab-ci.yml, CHANGELOG.md
=> Feature changelog

CHANGELOG.md, src/BnBTree.jl, src/bb_strategies.jl, src/fpump.jl, src/model.jl, test/user_limits.jl
First step for #88 
Still need to specify a time limit on the nlp solver if needed.
=> Bugfix time limit

.travis.yml, test/REQUIRE, test/basic.jl, test/fpump.jl, test/parallel.jl, test/runtests.jl
=> Cbc in test

.travis.yml, src/Juniper.jl, src/model.jl, src/solver.jl, test/basic.jl
Maximization problem 5/6 instead of 1/6
=> use correct gain_mu

CHANGELOG.md, src/BnBTree.jl, src/bb_gains.jl, src/bb_inits_and_defaults.jl, src/bb_strategies.jl, src/debug.jl, src/model.jl, src/types.jl, src/util.jl
- Add linear constraints using `@constraint`
- Use DFS on all nodes with the best score
- Renaming of variables from integer to discrete 
The first part drastically improves the speed of Juniper
Additionally adding quadratic constraints that way would be reasonable.
Need to check whether a constraint is quadratic here as `isconstrquadratic` doesn't exist
=> Feature lin constr and BFS+DFS

CHANGELOG.md, src/bb_strategies.jl, src/bb_type_correct.jl, test/POD_experiment/blend029.jl, test/pod.jl
The bug appeared in the moi branch but didn't have any occurrences yet in the master branch. 
Appears during strong branching if a variable has a highest gain but should be resolved if a tested variable afterwards is infeasible in one of it's children. Then the `node.solution` will be changed based on the other feasible child. This should only be done if the previously best variable candidate is not already discrete in that solution.
=> WIP: bugfix if max_gain_var is integer in solution init_strong_restart

.gitignore, src/model.jl, src/types.jl, test/basic.jl, test/parallel.jl, test/runtests.jl
=> Feature start value

src/BnBTree.jl, src/bb_strategies.jl, src/model.jl, src/table_log.jl, test/basic.jl
If best bound was equal to the objective value it was trapped in an endless loop.
Happened especially for feasibility problems.
=> Bugfix print table

CHANGELOG.md, Project.toml, REQUIRE, src/MOI_wrapper/MOI_wrapper.jl, src/model.jl, src/solver.jl, src/types.jl, test/REQUIRE, test/basic.jl, test/fpump.jl
=> Feature userfunction

Project.toml, test/minlp_tests.jl, test/runtests.jl
=> WIP: minlp tests package (3 exceptions)

CHANGELOG.md, docs/src/options.md, src/BnBTree.jl, src/MOI_wrapper/MOI_wrapper.jl, src/MOI_wrapper/results.jl, src/bb_gains.jl, src/bb_inits_and_defaults.jl, src/bb_integral_or_branch.jl, src/bb_strategies.jl, src/bb_user_limits.jl, src/debug.jl, src/fpump.jl, src/model.jl, src/solver.jl, src/types.jl, src/util.jl, test/basic.jl, test/functions.jl, test/pod.jl
Don't call objective value if status isn't optimal.
=> bugfix #130

CHANGELOG.md, Project.toml, src/fpump.jl, test/basic.jl, test/fpump.jl, test/runtests.jl
Maybe add the test case from the issue with GLPK @ccoffrin ?
=> bugfix #143

.gitignore, src/util.jl, test/fpump.jl
This should solve your issue #145 @rb004f
=> solves #145

.travis.yml
=> Minor updates to travis build

src/util.jl, test/basic.jl
=> Add check for JuMP.VariableRef expr_dereferencing!

CHANGELOG.md, src/MOI_wrapper/MOI_wrapper.jl, src/model.jl, src/util.jl, test/basic.jl, test/parallel.jl, test/user_limits.jl
Adding an incumbent solution if the given start value provides a solution to the problem.
=> Implementation of #167: Start value incumbent

.travis.yml, docs/make.jl
=> Maintenance on CI Config

.gitignore, CHANGELOG.md, src/fpump.jl, src/model.jl, src/util.jl, test/basic.jl
Copying the expression instead of mutating it in the expression graph.
Fix #184
=> Bugfix nlexpressions

CHANGELOG.md, Project.toml, src/fpump.jl, src/model.jl, src/util.jl, test/fpump.jl
=> Registered functions didn't get registered in fpump

test/fpump.jl
=> test case for #192

CHANGELOG.md, docs/src/options.md, src/MOI_wrapper/MOI_wrapper.jl, src/fpump.jl, src/solver.jl, src/types.jl, test/functions.jl
option to set `JUNIPER_RNG` with `seed::Int64`.
=> option seed + changelog

CHANGELOG.md, Project.toml, test/basic.jl, test/fpump.jl
Unfortunately the fix for #195 got directly into master. This changes the location of the test case and adds a line to the changelog.
Will register v0.6.4 when the tests pass
=> moved test case and added changelog

.travis.yml
Testing on the new Julia v1.5 instead of v1.4 now
=> testing julia 1.5

CHANGELOG.md, Project.toml, src/bb_inits_and_defaults.jl, test/basic.jl
Bugfix for #201 
This converts the optimizer to an optimizer with attributes in all cases.
Haven't added a test for this yet as it creates quite some output from Ipopt.
=> Bugfix when optimizer without attributes

Project.toml, test/conic.jl, test/runtests.jl
Closes #213 
There's plenty of room for adding more complicated test functions. But this at least tests some of the code paths.
=> Add test for conic subsolver

test/conic.jl
Closes #212
There's no need to modify Juniper or Ipopt.
=> Add test for conic model with Ipopt

src/fpump.jl, src/model.jl
=> Fix 269 by adding a cache around each of the subsolvers
